### ISSUE TITLE
Google search / Schema.org

### ISSUE THREAD

**Issue by ghost** [gmfmi/searchinGhost#16]
With this script is there a way to tell google with a schema on how to use the search option?

Thank you

**Comment by gmfmi** [comment]
I am not aware of what you are talking about. Do you have any reference or documentation on the subject?

**Comment by ghost** [comment]
It's called sitselinks search box. Would be great to have this.

https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox

**Comment by gmfmi** [comment]
Well, I think it is doable but I do not think it is a good idea.

First, if you want to set it up, you need to create a page in your blog that will display search results (e.g. `/search/?q=hello`). Then, you can add the hole sitelinks code in your header and it should work as expected.

But even if it is OK on the Google side, I do not think the "human" user experience will be worth it. The main issue here is that searchinghost is making things easy because everything is done within the user browser. In the end, your users will wait for searchinghost to be downloaded, initialized, to fetch all articles, compute search terms and only then display the results on the page. On small websites, it will probably be fast enough but on real case scenarios... (not to mention network issues).

To conclude, if I were you, I would only use sitelinks with a real backend search engine.
